CREATE TABLE IF NOT EXISTS USERS
(
  USER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  LOGIN VARCHAR(32),
  PASSWORD VARCHAR(64),
  EMAIL VARCHAR(32),
  PRIMARY KEY(USER_ID),
  UNIQUE(LOGIN)
);

CREATE TABLE IF NOT EXISTS TASKS
(
  TASK_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(128),
  DESCRIPTION VARCHAR(64),
  ESTIMATED INT(32),
  PRIMARY KEY(TASK_ID),
  UNIQUE(NAME)
);
